server:
  port: 8090
spring:
  application:
    name: "message"
  cloud:
    stream:
      bindings:
        send-out-0:
          destination: send-communication
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    connection-timeout: 10s
