
spring:
  application:
    name: "message"
  cloud:
    function:
      definition: funcOne|funcTwo
    stream:
      bindings:
        funcOnefuncTwo-in-0:
          destination: send-communication
          group: ${spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    connection-timeout: 10s
server:
  port: 8888
